### ISSUE TITLE
autoFixOnSave not working

### ISSUE THREAD

**Issue by cortopy** [Microsoft/vscode-tslint#136] opened 2016-11-24 13:20 UTC
I currently have the following two settings:

```json
{
    "tslint.enable": true,
    "tslint.autoFixOnSave ": true,
}
```

but tsLint autofixer doesn't run on save. If I run it manually it fixes the problems though.

Visual Studio Code version: 1.7.2
tslint: 4.0.2
tslint extension: 0.6.4

**Comment by egamma** [comment] 2016-11-24 14:20
@cortopy what is your setting for 	
```json
"files.autoSave": "???",
```
Notice that `autoFixOnSave` is ignored when `files.autoSave` is set to `afterDelay`.

**Comment by cortopy** [comment] 2016-11-24 17:09
I don't have any setting for `autoSave`. I've tried with "off" and "onFocusChange" but same result.

This is my full user config (no workspace config apart from location of typescript):

```json
{
    "editor.tabSize": 2,
    "editor.insertSpaces": true,
    "files.eol": "\n",
    "eslint.autoFixOnSave": true,
    "tslint.enable": true,
    "tslint.autoFixOnSave ": true,
    "window.zoomLevel": 0
}
```

**Comment by egamma** [comment] 2016-11-25 17:16
There is another restriction in that the code will not do an autofix if a document has been modified during the 'onWillSave' event. This can happen when you have a formatter extension that also formats your document on Save. Can you try this again with disabled formatter extensions?

I will work on removing this restriction, but first we must make the tslint auto fixes more robust.

Just as a demo that it works IFF you have only tslint autofix enabled as an 'onWillSave' handler.

![tslint-fix-onsave](https://cloud.githubusercontent.com/assets/172399/20632067/0efcfff0-b33b-11e6-8675-a756e2fe9de0.gif)

**Comment by cortopy** [comment] 2016-11-29 09:57
@egamma I'm not sure I understand what you mean. I don't have any extension that formats typescript files apart from tslint. Just in case I've tried disabling eslint (autosave formatting works for js files)  and the default editor `formatOnSave`. I still can't get it to work

**Comment by egamma** [comment] 2016-11-29 10:00
@cortopy ok, then can you olease help  me to reproduce what you see by sharing your `tslint.json` and some sample.ts file that exposes the problem.

**Comment by cortopy** [comment] 2016-11-29 10:03
Sure, this is my `tslint.json` file:

```json
{
  "rulesDirectory": ["node_modules/codelyzer"],
  "rules": {
    "align": [true, "parameters", "statements"],
    "max-line-length": [true, 200],
    "no-inferrable-types": true,
    "class-name": true,
    "comment-format": [
      true,
      "check-space"
    ],
    "indent": [
      true,
      "spaces"
    ],
    "eofline": false,
    "no-duplicate-variable": true,
    "no-eval": true,
    "no-arg": true,
    "no-internal-module": true,
    "no-trailing-whitespace": true,
    "no-bitwise": false,
    "no-shadowed-variable": true,
    "no-unused-expression": true,
    "no-unused-variable": true,
    "one-line": [
      true,
      "check-catch",
      "check-else",
      "check-open-brace",
      "check-whitespace"
    ],
    "quotemark": [
      true,
      "double",
      "avoid-escape"
    ],
    "semicolon": [true, "always"],
    "typedef-whitespace": [
      true, {
        "call-signature": "nospace",
        "index-signature": "nospace",
        "parameter": "nospace",
        "property-declaration": "nospace",
        "variable-declaration": "nospace"
      }
    ],
    "curly": false,
    "variable-name": [
      true,
      "ban-keywords",
      "check-format",
      "allow-trailing-underscore"
    ],
    "whitespace": [
      true,
      "check-branch",
      "check-decl",
      "check-operator",
      "check-separator",
      "check-type"
    ],
    "directive-selector-name": [true, "camelCase"],
    "component-selector-name": [true, "kebab-case"],
    "directive-selector-type": [true, "attribute"],
    "component-selector-type": [true, "element"],
    "use-input-property-decorator": true,
    "use-output-property-decorator": true,
    "use-host-property-decorator": true,
    "no-input-rename": true,
    "no-output-rename": true,
    "use-life-cycle-interface": true,
    "use-pipe-transform-interface": true,
    "component-class-suffix": true,
    "directive-class-suffix": true
  }
}
```

In regards to file, the one you were already using should be enough. I always use double quotemarks, and I was amazed at seeing how it works for you.

**Comment by nukuuk** [comment] 2016-11-30 20:41
Am having the same problem.  Nor does the auto-correct lightbulb appear as well....

**Comment by egamma** [comment] 2016-11-30 20:46
@nukuuk the lightbulb only appears for warnings that have fixes. In tslint 4.0 not all warnings have fixes. Please check out this blog post for a list of available fixers https://palantir.github.io/tslint/2016/11/17/new-for-4.0.html.

The quick fix for quotes was a custom implementation inside vscode that has been removed in favor of fully supporting the fixes provide by tslint.

**Comment by egamma** [comment] 2016-11-30 21:57
@cortopy I'm sorry but I'm still unable to reproduce. I'm using your `tslint.json`. Please see the attached demo.

Can you share with me:
- your workspace settings  `Preferences>WorkspaceSettings` 
- your user settings `Preferences>UserSettings` 
- a .ts file that exihibits the problem

I'v recorded the demo on Windows, what platform are you using?

![tslint-fix-onsave2](https://cloud.githubusercontent.com/assets/172399/20772985/1f875870-b750-11e6-8a80-55cbd9fa64b3.gif)

**Comment by nukuuk** [comment] 2016-12-01 03:53
@egamma  so if I select F1 then "TSLint:  Fix all auto-fixable problems," then...what is supposed to happen? No problems are fixed for me.   I have the same settings as @cortopy

**Comment by beylkhanovdamir** [comment] 2016-12-01 09:10
it's not working for me too
see my short screencast [on this link](http://www.screencast.com/t/vj2s2EN3)

**Comment by beylkhanovdamir** [comment] 2016-12-01 09:14
@egamma 

btw, vs code shortcut (**ctrl+.**) to fix warning issues is not working

**Comment by egamma** [comment] 2016-12-01 09:14
Thank you for the screen cast. Please see my comment above https://github.com/Microsoft/vscode-tslint/issues/136#issuecomment-264119379.  Please provide a test case that I can reproduce and include the artifacts as described above.

Also notice there is no quick fix for quoted strings
![image](https://cloud.githubusercontent.com/assets/172399/20787984/eadab07c-b7ae-11e6-8fa6-24bfa11b6284.png)

**Comment by egamma** [comment] 2016-12-01 09:21
>k, got it. But in prev.version of tslint I can to fix the quoted strings issue with using vs code shortcut (ctrl+.).
in current version of tslint I cannot to fix it

pls see this comment: https://github.com/Microsoft/vscode-tslint/issues/144#issuecomment-264121538

When there is no quick fix, there is no light bulb and there is no command to be executed on CTRL+.

**Comment by beylkhanovdamir** [comment] 2016-12-01 09:24
@egamma 
ok, would be better include this fix in new release

**Comment by nukuuk** [comment] 2016-12-01 19:33
ok its understood that the lightbulb fixer and CTRL+ as been deprecated.  But the tslint fixing still seems to be broken.  Here is my [screencast](http://www.screencast.com/users/brando39/folders/Default/media/d2db875c-89c8-465d-ae1f-75c0dee44fbb) on the issue.

**Comment by egamma** [comment] 2016-12-01 21:25
@nukuuk thanks for the screencast and I totally believe you, but please do not have my type-in the setup from the screencast by hand, but attach the tslint.son and subset of the  .ts file (it can have compile errors) that your are trying to auto fix  (pls see also https://github.com/Microsoft/vscode-tslint/issues/136#issuecomment-264118367).

**Comment by cgatian** [comment] 2016-12-02 00:55
This is also happening to me after upgrading from 0.6.0 to 0.6.7.  

tslint: 3.15.1
vscode: 1.7.2

Updating tslint to 4.0.2 did not help.

**Comment by nukuuk** [comment] 2016-12-02 04:15
@cgatian many thanks that worked great!

**Comment by egamma** [comment] 2016-12-02 07:07
@nukuuk @cortopy one thing I should also make clear. In releases prior to vscode-tslint 0.6.0 there was support for quick fixes with all versions of tslint. This was implemented inside vscode only. Since 0.6.0 quick fixes are only available when tslint supports it. Tslint added quick fixes in version 3.17.* is that there is no more quick fix support anymore when you use tslint version 3.15.1.

So when you do not want to upgrade to tslint 4.0 but still have quick fixing support then you need upgrade to tslint 3.17.*. However, in this version only the missing semicolon quick fix was available.

@nukuuk can I close this issue?

**Comment by nukuuk** [comment] 2016-12-02 08:29
@egamma all I know is that if I upgrade to vscode-tslint 0.6.7 and use tslint 4.0.2 (locally and globally) then quick fix does not work.  If I downgrade to 0.6.0/3.15.1 then it works.  I can roll with this until a real fix to the quick fix come out, or I discover how to resolve conflicting formatters, bad config files or whatever the issue is. Thanks for your help.

**Comment by cgatian** [comment] 2016-12-02 10:27
@egamma I was using tslint 4.x and 0.6.7 and there were no quick fixes. 

Are you saying the plugin (vs code tslint's) now relies on tslint's quick fixes, and not the plugin's, and since tslint's hasn't implemented all the available quick fixes the vscode plugin provided that's why they are not available?

**Comment by cortopy** [comment] 2016-12-02 11:27
@egamma I've created this [repo](https://github.com/cortopy/tslint-debug) with all the info you requested (I think), including the following screencast where you can see saving the file doesn't trigger autofix. I can manually trigger it though. I'm sticking to the title of my issue (i.e.: my case is about autoFixOnSave, not quick fix in general)

It's a shame about the double quotes in the newer versions, but in this file I've also included semicolons at end of line to test it.

![screencapture](https://cloud.githubusercontent.com/assets/8725825/20832378/e8d70838-b881-11e6-9116-032671583c10.gif)

**Comment by egamma** [comment] 2016-12-03 09:14
@cortopy great thanks I'll look into it as soon as possible

@beylkhanovdamir I've revived the quick fix for quotemarks (' should be ") in 0.7.0.

**Comment by egamma** [comment] 2016-12-04 18:38
@cortopy there is an issue in your [settings file at line 8](https://github.com/cortopy/tslint-debug/blob/master/user-settings.vscode.json#L8).

```json
>"tslint.autoFixOnSave ": true,
```
notice the trailing space after 'tslint.autoFixOnSave'. When I fix this to
```json
>"tslint.autoFixOnSave": true,
```
Then it works for me when using vscode-tslint 0.7.0 which has the quotemark quick fix re-enabled. 
@cortopy can you please confirm that this works after this tweak for you as well?

![tslint-fix-onsave3](https://cloud.githubusercontent.com/assets/172399/20868299/9a7acb92-ba58-11e6-94d9-7ebae8a128c3.gif)

**Comment by egamma** [comment] 2016-12-04 18:46
@cgatian 

>Are you saying the plugin (vs code tslint's) now relies on tslint's quick fixes, and not the plugin's, and since tslint's hasn't implemented all the available quick fixes the vscode plugin provided that's why they are not available?

This was correct until yestereday and version 0.7.0, based on feedback I've revived the quick fix for the `quotemark` rule. I'm willing to revive some more custom fixes.

**Comment by cortopy** [comment] 2016-12-06 20:55
@egamma that was it!! thanks so much for looking into it 

I would normally close the issue now, but since there have been references and discussions of other topics not sure if I should

**Comment by egamma** [comment] 2016-12-06 21:01
@cortopy happy end 🌷 , thanks for not giving up. BTW, we will add a warning to avoid such typos in the future. 

Since your issue has been addressed I'm closing this one, Remember `one bug per issue` and I think the other `piggyback issues` have been addressed by now. If not then separate issues should be opened for them.

**Closed by egamma** 2016-12-06 21:01 UTC
