### ISSUE TITLE
After updating TSLint it stoped working

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [Microsoft/vscode-tslint#190] opened 2017-04-10 10:53 UTC
version: 4.5.1
Stack trace: 
ypeError: Cannot read property 'indexOf' of undefined
    at Rule.apply (c:\...\node_modules\tslint\lib\rules\noTrailingWhitespaceRule.js:41:31)
    at Linter.applyRule (c:\...\node_modules\tslint\lib\linter.js:138:33)
    at Linter.lint (c:\...\node_modules\tslint\lib\linter.js:104:41)
    at doValidate (C:\Users\...\.vscode\extensions\eg2.tslint-0.11.0\server\server.js:369:20)
    at validateTextDocument (C:\Users\...\.vscode\extensions\eg2.tslint-0.11.0\server\server.js:285:27)
    at Delayer.d.trigger [as task] (C:\Users\...\.vscode\extensions\eg2.tslint-0.11.0\server\server.js:462:9)
    at completionPromise.Promise.then (C:\Users\...\.vscode\extensions\eg2.tslint-0.11.0\server\delayer.js:19:35)
[Info  - 1:43:09 PM] vscode-tslint: 'Cannot read property 'indexOf' of undefined' while validating:

**Comment by egamma** [comment] 2017-04-10 12:59
@vytautas-pranskunas- can you please share the section from the tslint.json that configures the white space rule? It looks like the actual exception happens inside a tslint rule.

Can you reproduce the problem when you try it with tslint 5.0.0?

**Comment by vytautas-pranskunas-** [comment] 2017-04-11 06:21
{
    "rulesDirectory": [
        "node_modules/codelyzer",
        "node_modules/tslint-eslint-rules/dist/rules"
    ],
    "rules": {
        // tslint rules
        "class-name": true,
        "comment-format": [ true, "check-space" ],
        "no-console": [
            true,
            "debug",
            "info",
            "time",
            "timeEnd",
            "trace",
            "log"
        ],
        "indent": [ true, "spaces" ],
        "max-line-length": [ true, 140 ],
        "no-debugger": true,
        "no-duplicate-variable": true,
        "no-eval": true,
        "no-internal-module": true,
        "no-trailing-whitespace": true,
        "no-reference": true,
        "no-var-keyword": true,
        "one-line": [
            true,
            "check-open-brace",
            "check-whitespace"
        ],
        "quotemark": [ true, "single" ],
        "semicolon": [ true, "always" ],
        "triple-equals": [ true, "allow-null-check" ],
        "typedef-whitespace": [
            true,
            {
                "call-signature": "nospace",
                "index-signature": "nospace",
                "parameter": "nospace",
                "property-declaration": "nospace",
                "variable-declaration": "nospace"
            }
        ],
        "variable-name": [ true, "ban-keywords" ],
        "whitespace": [
            true,
            "check-branch",
            "check-decl",
            "check-operator",
            "check-separator",
            "check-type"
        ],
        // tslint-eslint rules
        "no-duplicate-case": true,
        "no-extra-semi": true,
        "no-irregular-whitespace": true,
        "valid-typeof": true,
        // codelyzer rules
        "directive-selector": [true, "attribute", "ta", "camelCase"],
        "component-selector": [true, "element", "ta", "kebab-case"],
        "use-input-property-decorator": true,
        "use-output-property-decorator": true,
        "use-host-property-decorator": true,
        "no-attribute-parameter-decorator": true,
        "no-input-rename": true,
        "no-output-rename": true,
        "no-forward-ref" :true,
        "use-life-cycle-interface": true,
        "use-pipe-transform-interface": true,
        "pipe-naming": [true, "camelCase", "ta"],
        "component-class-suffix": true,
        "directive-class-suffix": true
    }
}

**Comment by vytautas-pranskunas-** [comment] 2017-04-11 06:32
p.s. I cannot upgrade to ^5.0.0 because codalyzer need tslint 4.0.0

**Comment by egamma** [comment] 2017-04-11 06:59
@vytautas-pranskunas- I've tried to reproduce this with your tslint.json and your rules and I'm not able to do so. See below.

- can you reproduce this exception when you run tslint from the commandline on your project?
- this exception can happen when the rule fails on a particular file. However, this information is not included in your stack trace above there is no text after `while validating:`. 
>[Info - 1:43:09 PM] vscode-tslint: 'Cannot read property 'indexOf' of undefined' while validating:

Can you open the dev console and check the log when this happens (`Help>Toggle Developer Tools`).

![image](https://cloud.githubusercontent.com/assets/172399/24896229/4312f6a4-1e94-11e7-8b3c-877d825759da.png)

**Comment by vytautas-pranskunas-** [comment] 2017-04-11 08:14
I have reinstalled all npm packages once again and it is gone... Not sure why it was happening yesterday (i did clean reinstall too).

**Comment by egamma** [comment] 2017-04-12 19:49
Closing - no further action planned on this one.

**Closed by egamma** 2017-04-12 19:49 UTC
