### ISSUE TITLE
Failed to load the TSLint library for the document, when tslint is installed globally

### ISSUE THREAD

**Issue by TestUser013** [Microsoft/vscode-tslint#384] opened 2018-08-27 12:35 UTC
- tslint version: 5.11.0 (tslint -v) (global installation)
- typescript version: 2.9.2 (tsc -v) (global installation)
- npm version: 5.6.0 (npm -v)
- nodejs version: 8.11.4 (node -v)
- vscode version: 1.26.1 portable (with "data" folder)

I got an error in output of TSLint extension.

> Failed to load the TSLint library for the document c:\WORK\******\testLint.ts
> 
> To use TSLint in this workspace please install tslint using 'npm install tslint' or globally using 'npm install -g tslint'.
> TSLint has a peer dependency on `typescript`, make sure that `typescript` is installed as well.
> You need to reopen the workspace after installing tslint.

I don't have any error when I ran tslint from VSCode terminal or from windows terminal. How can I check what is the problem? 

Here is verbose output ("tslint.trace.server": "verbose"):
[TSLint.log](https://github.com/Microsoft/vscode-tslint/files/2323835/TSLint.log)

**Comment by egamma** [comment] 2018-08-27 12:50
@TestUser013 some more questions:

- what version of vscode-tslint do you have installed. You can see the version in the Extension Viewlet.
- can you share more information about your setup. Do you have tslint installed locally or globally? Do you have TS installed locally or globally?
- Since this looks like a test setup, can you share the test setup with me, e.g., check it into a github repo?

**Comment by egamma** [comment] 2018-08-27 14:37
I can reproduce the problem. It was a bug introduced in the last refactoring.

Fixed in 1.0.38, that I´ve just published.

**Closed by egamma** 2018-08-27 14:37 UTC
