### ISSUE TITLE
Rules: strict-boolean-expressions & Rule: no-floating-promises

### ISSUE THREAD

**Issue by ohrrkan** [Microsoft/vscode-tslint#311] opened 2018-01-04 16:48 UTC
- tslint Version: 5.8.0
- typescript Version: 2.6.2

Steps to Reproduce:

Hello,

Happy new year! 

https://palantir.github.io/tslint/rules/strict-boolean-expressions/
https://palantir.github.io/tslint/rules/no-floating-promises/

Those two rules do not seems to be handle by vscode-tslint. Got the tslint error on compile but do not have alerte in Vscode.

**Comment by egamma** [comment] 2018-01-05 11:45
@ohrrkan I wish you a great new year as well. Both of the rules you use require type information and rules that need type information are not supported. See https://github.com/Microsoft/vscode-tslint/issues/70#issuecomment-241041929. Closing as a duplicate of #70.

**Closed by egamma** 2018-01-05 11:45 UTC
