### ISSUE TITLE
Extension reports "no-trailing-whitespace" tslint configuration setting to be in error

### ISSUE THREAD

**Issue by cmccall** [Microsoft/vscode-tslint#237] opened 2017-07-29 23:33 UTC
I'm defining a no-trailing-whitespace rule in tslint.json as an array:
`        "no-trailing-whitespace": [
            true,
            "ignore-comments"
        ],
`

This appears to be inline with the spec, as documented here: https://palantir.github.io/tslint/rules/no-trailing-whitespace/

However, the extension highlights this section of tslint.json as an error, reporting "Incorrect type. Expected boolean". I couldn't tell if this was an error in the extension itself or was coming from tslint - I tried to turn on trace debugging to see messages from the server and did not see that error, so I am assuming this is an issue in the extension somewhere.

This is using
    "tslint": "^5.5.0",
    "typescript": "^2.4.2"

**Comment by egamma** [comment] 2017-08-01 13:14
This looks like a duplicate of the upstream issue #192. A PR against the schemastore would be appreciated, pls see https://github.com/Microsoft/vscode-tslint/issues/192#issuecomment-301022511

**Closed by egamma** 2017-08-01 13:14 UTC
