### ISSUE TITLE
tslint show error on @types file

### ISSUE THREAD

**Issue by hkjeffchan** [Microsoft/vscode-tslint#364] opened 2018-07-09 14:48 UTC
- tslint Version: 5.10.0 (install globally or locally, tried both)
- typescript Version: 2.9.2 (install globally or locally, tried both)

"tslint.ignoreDefinitionFiles": true

Steps to Reproduce:

1. Command Click the related funciton to open the definition file
2. Tslint will report error on "PROBLEMS" panel

**Comment by hkjeffchan** [comment] 2018-07-09 14:53
Extensions Version:
  Angular-BeastCode v6.0.21
  angular2-inline v0.0.17
  angular2-switcher v0.1.9
  beautify v1.3.2
  bracket-pair-colorizer v1.0.59
  code-settings-sync v2.9.2
  debugger-for-chrome v4.7.0
  dotenv v1.0.1
  gc-excelviewer v2.1.24
  git-project-manager v1.6.1
  githistory v0.4.1
  github-3 v1.1.1
  github-plus-theme v1.1.3
  gitignore v1.0.1
  gitlens v8.4.1
  graphql-for-vscode v1.12.0
  html-css-class-completion v1.17.1
  html-snippets v0.2.1
  JavaScriptSnippets v1.7.0
  markdown-all-in-one v1.5.1
  markdown-extended v0.9.2
  markdown-shortcuts v0.8.1
  nestjs v0.4.0
  ng-template v0.1.9
  php-debug v1.12.3
  php-docblocker v1.6.0
  prettier-now v1.4.9
  rainbow-csv v0.4.2
  sass-indented v1.4.9
  smarty v0.3.0
  theme-cobalt2 v2.1.6
  transformer v1.6.0
  tslint v1.0.33
  vscode-great-icons v2.1.36
  vscode-intelephense-client v0.8.8
  vscode-stylesheet-formatter v0.2.0

**Comment by egamma** [comment] 2018-07-09 15:54
@hkjeffchan both TypeScript and TS Lint can report errors for this file. A screenshot of the Problems View would make this clear. 

Errors from tslint have the error message prefix `[tslint]` errors from Typescript have the error message prefix `[ts]`.

**Comment by egamma** [comment] 2018-07-10 08:45
>It is from [ts] and thanks for helping me narrow down the problem. I already added "node_modules" in "exclude" under tsconfig.json but it still reports the problem when I open the definition.


I can reproduce the behavior that TypeScript validates excluded files when opened in the VS Code editor. I suggest to file an issue in the vscode repository to discuss this issue. 

>I think vscode-tslint doesn't read tsconfig.json, you can add exclude to tslint.json

Yes, this is the current behavior of tslint, the tslint options are configured in 'tslint.json'.

I´m closing the issue, since it isn´t an issue in vscode-tslint.

**Closed by egamma** 2018-07-10 08:45 UTC
