### ISSUE TITLE
False 'Could not find config file at ...' Message

### ISSUE THREAD

**Issue by bm-stschneider** [Microsoft/vscode-tslint#353] opened 2018-06-08 07:00 UTC
Issue Type: <b>Bug</b>
Although I have a "tslint.configFile" set I get an error from TSLint.

[Info  - 08:58:20] vscode-tslint: Status is OK
[Info  - 08:58:20] vscode-tslint: Cannot read tslint configuration - 'Could not find config file at: `<pwd>/tsconfig.json`'

Extension version: 1.0.30
VS Code version: Code - Insiders 1.25.0-insider (8f8ed32e737a7a906fac654fb0bd61b257b449b1, 2018-06-08T05:10:42.592Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_1057026|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by egamma** [comment] 2018-06-08 07:03
@bm-stschneider are you using an absolute or relative path? Does an absolute path work?

**Comment by egamma** [comment] 2018-06-08 15:52
I cannot reproduce this I have a tslint.json in `c:\test\tslint.json  and my workspace settings are configured as below and the linting works as expected. What is different between your and this setup?

```json
{
    "tslint.configFile": "c:/test/tslint.json"
}
```

**Comment by egamma** [comment] 2018-06-08 16:07
(closed by accident)

**Comment by bm-stschneider** [comment] 2018-06-11 05:55
Only difference I see is that I"m using macOS.
`"tslint.configFile": "/Users/stschneider/tsconfig.json",`

**Closed** 2018-06-11 06:04 UTC
Labels: needs more info
