### ISSUE TITLE
funky error message about not able to parse package.json

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode-tslint#26] opened 2016-01-19 16:03 UTC
it has a comment

```
vscode-tslint: '/Users/jrieken/Code/_samples/extensions/virtual/package.json: Unexpected token /' while validating: file:///Users/jrieken/Code/_samples/extensions/virtual/src/extension.ts stacktrace: SyntaxError: /Users/jrieken/Code/_samples/extensions/virtual/package.json: Unexpected token /
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:460:27)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Function.findConfiguration (/Users/jrieken/.npm-packages/lib/node_modules/tslint/lib/configuration.js:42:27)
    at getConfiguration (/Users/jrieken/.vscode/extensions/eg2.tslint-0.5.8/server/server.js:45:31)
    at doValidate (/Users/jrieken/.vscode/extensions/eg2.tslint-0.5.8/server/server.js:104:29)
    at validateTextDocument (/Users/jrieken/.vscode/extensions/eg2.tslint-0.5.8/server/server.js:77:9)
```

**Comment by egamma** [comment] 2016-01-19 17:00
Please try to reproduce using the latest vscode-tslint.

**Comment by egamma** [comment] 2016-02-12 10:03
This was caused by an older tslint version - closing

**Closed by egamma** 2016-02-12 10:03 UTC
Labels: bug
