### ISSUE TITLE
tslint.json linting error

### ISSUE THREAD

**Issue by michael-yx-wu** [Microsoft/vscode-tslint#217] opened 2017-06-08 15:36 UTC
`tslint` supports `tslint.json` rule configurations taking objects, but this plugin only thinks that `array`, and `boolean` types are allowed. For example, the following is valid configuration but the plugin doesn't think so:

![screen shot 2017-06-08 at 11 34 43 am](https://user-images.githubusercontent.com/3681045/26937176-afe7815a-4c3e-11e7-8730-4dbb01c958c9.png)

**Comment by egamma** [comment] 2017-06-28 19:50
Duplicate of #192

**Closed by egamma** 2017-06-28 19:50 UTC
Labels: duplicate
