### ISSUE TITLE
Tslint task output in vscode (problems tab) has relative routes that aren't working-

### ISSUE THREAD

**Issue by Pablocgdev** [Microsoft/vscode-tslint#281] opened 2017-10-19 09:07 UTC
![image](https://user-images.githubusercontent.com/9206972/31762977-28afbbf2-b4bd-11e7-82dd-555269a666d5.png)

I get two type of errors when trying to click on any of these Tslint warnings to navigate the file:

![image](https://user-images.githubusercontent.com/9206972/31763082-7bd4020c-b4bd-11e7-8598-d18e0ba93838.png)

![image](https://user-images.githubusercontent.com/9206972/31763088-81559524-b4bd-11e7-96f2-ae75c0fbe9d7.png)

Also as you can see the warning and errors are "chopped" 

![image](https://user-images.githubusercontent.com/9206972/31763075-713245d4-b4bd-11e7-8bfc-3d87975865b0.png)

I'm running it on `"tslint": "^5.7.0",` and my task file is:

`
{
    "version": "2.0.0",
    "tasks": [
        {      
            "type": "npm",
            "script": "lint",
            "problemMatcher": [
                "$tslint4"
            ]    
        }
    ]
}
`

**Comment by egamma** [comment] 2017-10-19 14:45
>I'm running it on  "tslint": "^5.7.0",  and my task file is:

If you are running tslint 5 then you should use the `tslint5` problem matcher and not `tslint4`. Can you please give it a try.

**Comment by Pablocgdev** [comment] 2017-10-19 15:16
Hello, I've tried tslint5 problem matcher and does not give any output at all in vscode (it shows the console output correctly).

Also, I've updated the project to tslint 5 just for testing purposes, I was having the same issues with 4.x.x tslint.

Thanks for your help.

**Comment by egamma** [comment] 2017-10-24 14:33
@Pablocgdev I cannot reproduce this problem with tslint 5.7 and the tslint5 problem matcher. Here is the setup https://github.com/Microsoft/vscode-tslint/tree/master/tslint-tests.

To try it out:
- git clone https://github.com/Microsoft/vscode-tslint
- cd tslint-tests
- npm install
- code .
- Tasks>Run Tasks  'gulp tslint'.

What is different in your setup?
Can you attach the output from your gulp run when you use tslint 5?

**Comment by egamma** [comment] 2017-11-03 12:51
Closing since I cannot reproduce. Please reopen with steps for how to reproduce.

**Closed by egamma** 2017-11-03 12:51 UTC
