### ISSUE TITLE
Error: Path must be a string. Received null

### ISSUE THREAD

**Issue by Ristaaf** [Microsoft/vscode-tslint#5] opened 2015-11-20 13:08 UTC
I get this error every time when opening a comparison of a ts file in the GIT panel of VS Code. Happen in all projects I have tried, including a test one with just one simple ts file.

**Comment by serkanyersen** [comment] 2015-11-23 22:23
Same here.

**Comment by egamma** [comment] 2015-11-26 15:20
This is unrelated to vscode-tslint. Moving to vscode.

**Comment by egamma** [comment] 2015-11-26 15:21
This issue was moved to Microsoft/vscode#711

**Comment by serkanyersen** [comment] 2015-11-26 21:37
this error is specifically caused by this extension. it goes away when you uninstall ts-lint on vscode. Why do you think it's unrelated to ts-lint?

**Comment by egamma** [comment] 2015-11-26 23:11
Reopening, thanks for the additional info that the error goes away when ts-lint is uninstalled.

**Closed** 2015-11-26 23:33 UTC
