### ISSUE TITLE
VS code. The "Fix all autofixable" option behave unexpectidly

### ISSUE THREAD

**Issue by Kirill486** [Microsoft/vscode-tslint#381] opened 2018-08-21 14:21 UTC
- tslint Version:5.9.1
- typescript Version:3.0.1 (just updated from later one, have no idea how to find out which one exactly)

Steps to Reproduce:

1. Open .tsx or .ts file
2. Point cursor to highlited violated rule
3. Press the bulb button (context menu should appear)

Sometimes option  "Fix all auto-fixable" do not show up and even if it does it does nothing (do not fix broken rules at all).
Option "Fix all ${a ts lint rule that got violated}" fixes code meanwhile, but sometimes does not show up either.
Ubuntu 18.04.1 LTS
VS Code Version: 1.26.1
TS Lint plug-in for VS Code v1.0.36

**Comment by egamma** [comment] 2018-08-22 07:49
I suspect this is caused by overlapping changes. When the changes overlap then fix all currently cannot apply them.

When this happens can you check whether there are overlapping rule failures.

**Comment by Kirill486** [comment] 2018-08-22 07:57
Yes, I can. Is there a guide somewhere about how to check are there any overlapping rule?

**Comment by egamma** [comment] 2018-08-22 08:08
When you hover over the squiggles do you see more than one rule failure. In the example below the range `isEqual` is covering two rule failures.

![image](https://user-images.githubusercontent.com/172399/44451187-4a7ad500-a5f3-11e8-9044-466156525b85.png)

**Comment by egamma** [comment] 2018-08-24 08:11
Actually the limitation shows up when the fix ranges overlap not the diagnostic ranges, something you cannot see in the UI. Fix all only applies fix ranges that do not overlap. 

Can you test that when this happens and you execute 'fix all' multiple times that then the fixes are applied.

**Comment by egamma** [comment] 2018-08-24 10:13
Suspect this is the same issue as #382

**Comment by egamma** [comment] 2018-08-27 07:13
In the latest version 1.0.37 vscode-tslint handles overlapping fixes. Can you pls keep an eye on whether this also addresses your problem.

**Comment by Kirill486** [comment] 2018-08-27 15:06
Yes, it does fix it. Thank you.

**Comment by egamma** [comment] 2018-08-28 06:56
closing, thanks for verifying.

**Closed by egamma** 2018-08-28 06:56 UTC
