### ISSUE TITLE
Simple issues not auto-fixable

### ISSUE THREAD

**Issue by jonsalvas** [Microsoft/vscode-tslint#233] opened 2017-07-25 11:24 UTC
I noticed that the extension is not able to auto-fix simple ts-lint warnings  "unused import" or "missing whitespace". Or am I missing any configuration options?

**Comment by egamma** [comment] 2017-07-26 09:30
@jonsalvas not all tslint rule failures are auto fixable. Do you see a light bulb when you select one of these warnings? Do you have the setting tslint.autoFixOnSave enabled?

**Comment by jonsalvas** [comment] 2017-07-26 09:35
Yes, I am aware of the fact that some failures are simply not fixable because they need human interaction, but I noticed that this also appears for simple issues like "missing whitespace" where I would expect that these can be fixed easily without any information deep information about the code or am I wrong?
Apparently I don't see any light bulb when hovering over the warnings and I am not using the autoFixOnSave-option but calling the autofix over the task runner.

**Comment by egamma** [comment] 2017-07-26 09:50
Did you check whether the tslint rule you are using has an auto fixer, this is documented here https://palantir.github.io/tslint/rules/ look for the 'Has Fixer' annotation.

**Comment by egamma** [comment] 2017-09-08 21:00
No additional insights provided, closing the issue. @jonsalvas pls reopen if you still see this issue.

**Closed by egamma** 2017-09-08 21:00 UTC

**Comment by kumarharsh** [comment] 2017-09-19 08:57
@egamma it seems like in the vscode insider builds 1.17, Fix all autofixable problems and Fix all <rule> doesn't work at all. Even for removing semicolons or replacing `'` with `"`.

**Comment by egamma** [comment] 2017-09-19 10:36
@kumarharsh just tried it and it works for me, both when I invoke the fixes from the light bulb or using the command palette action. Do the actions show up in the menu shown on the light bulb and they do nothing?

**Comment by kumarharsh** [comment] 2017-09-19 10:51
The actions do show up, but clicking the action, or even invoking it via the command palette does nothing. There is no output in the output pane too...

**Comment by kumarharsh** [comment] 2017-09-19 10:53
Btw, I'm working with tslint v5.0 - that might also be a reason... Let me see if downgrading fixes it.

**Comment by kumarharsh** [comment] 2017-09-19 11:57
@egamma yes, it works with 4.x. Some issue with tslint v5 I guess.

**Comment by egamma** [comment] 2017-09-19 13:35
@kumarharsh Works fine for me with tslint v5.7 can you try to upgrade.

**Comment by egamma** [comment] 2017-09-20 07:14
@kumarharsh also works for me with tslint 5.0. If you can reproduce the problem, please file a separate issue with steps to reproduce.

**Comment by kumarharsh** [comment] 2017-09-20 07:19
OK. Will do. Thanks for your time.
