### ISSUE TITLE
After using nodePath, syntax errors from tslint.json show up as "tslint not installed"

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-tslint#104] opened 2016-09-28 18:53 UTC
While testing https://github.com/Microsoft/vscode/issues/12603
1. Ensure tslint is not installed locally or globally and try linting
2. You will see 
   ![image](https://cloud.githubusercontent.com/assets/16890566/18927693/cedbb336-8571-11e6-96b1-b1a5abcdf32b.png)
3. Try to use tslint from some other location (not globally) by setting "tslint.nodePath" to that location
4. Output channel now says "Linter is running"
5. Make a syntax error in tslint.json
6. Output channel will look like the below instead of listing out the syntax error
   ![image](https://cloud.githubusercontent.com/assets/16890566/18927762/10f84d2e-8572-11e6-890d-73856e438be5.png)
7. Also the new status bar item does not appear at all. It should have appeared saying "TSLint: Error"

**Comment by egamma** [comment] 2017-05-07 15:50
I cannot reproduce this in the latest 0.1.12, closing

![image](https://cloud.githubusercontent.com/assets/172399/25782553/914ec5c8-334d-11e7-8cf6-651eca96bc18.png)

**Closed by egamma** 2017-05-07 15:50 UTC
