### ISSUE TITLE
Doesn't work with "promise-function-async": true rule

### ISSUE THREAD

**Issue by jaxxreal** [Microsoft/vscode-tslint#227] opened 2017-07-05 09:50 UTC
- **Extension version:** `0.16.0`
- **VSCode version:** `May 2017 (version 1.13)`
- **tslint package version:** `5.4.3`
- **typescript:** `2.1.5`

Case:
After adding `promise-function-async": true` line in `tslint.json`, extension doesn't show linting errors across project. After removing it, all works as usual.

**Comment by egamma** [comment] 2017-07-06 07:13
The rule `promise-function-async` requires type information https://palantir.github.io/tslint/rules/promise-function-async/. This is not supported, pls see the discussion in #70.

I cannot reproduce that adding this rule has a side effect on other linting rules, they still work.

Closing as a duplicate.

**Closed by egamma** 2017-07-06 07:13 UTC
Labels: duplicate
