### ISSUE TITLE
member-ordering - Incorrect type. Expected "object"

### ISSUE THREAD

**Issue by comerc** [Microsoft/vscode-tslint#241] opened 2017-08-19 08:51 UTC
VSCODE 1.15.1
EG2.TSLINT 0.17.0

![2017-08-19 11 48 18](https://user-images.githubusercontent.com/1025241/29485089-9255558a-84d4-11e7-8209-8109454912e9.png)

**Comment by CliveTeow** [comment] 2017-08-27 10:03
I am also facing the same issue.

**Comment by cchene** [comment] 2017-09-04 15:39
Problem is probably in the tslint.json, not in vscode-tslint: https://palantir.github.io/tslint/rules/member-ordering/

**Comment by egamma** [comment] 2017-09-04 15:46
Closing as a duplicate of #192

**Closed by egamma** 2017-09-04 15:46 UTC
