### ISSUE TITLE
Tslint extension is not installing in vscode, throws an error 

### ISSUE THREAD

**Issue by selvassn** [Microsoft/vscode-tslint#306] opened 2017-12-22 08:01 UTC
- tslint Version: 5.8.0
- typescript Version: 2.5.3
- vs code version: 1.19.1

Steps to Reproduce:

1. click on install button in vscode extention for ts 
2. throws ENOENT: no such file or directory, open 'C:\Users\424926\.vscode\extensions\eg2.tslint-1.0.24\package.json'

**Comment by egamma** [comment] 2017-12-23 09:36
@selvassn it looks like something when wrong with an update. I suggest to delete the folder C:\Users\424926.vscode\extensions\eg2.tslint-1.0.24 and you install vscode-tslint again. Sorry for the inconvenience. 

This looks like a duplicate of https://github.com/Microsoft/vscode/issues/36884.

**Closed by egamma** 2017-12-23 09:36 UTC

**Comment by houdinisparks** [comment] 2018-01-28 05:55
hi experiencing the same problem.

deleting the folder and installing it again does not solve the problem.
below are the logs output from Renderer:
`[2018-01-28 13:50:34.086] [renderer1] [trace] openWorkbench configuration {"_":[],"log":"trace","appRoot":"c:\\Program Files (x86)\\Microsoft VS Code\\resources\\app","machineId":"53c2b3a538c901147f1482cc99a16610cbd2fc336ac728c6a7aa5ab4e0e5826f","execPath":"C:\\Program Files (x86)\\Microsoft VS Code\\Code.exe","userEnv":{"VSCODE_IPC_HOOK":"\\\\.\\pipe\\fc9de6941718fa0d7cafb583d1992c7d-1.19.2-main-sock","VSCODE_NLS_CONFIG":"{\"locale\":\"en-us\",\"availableLanguages\":{}}","VSCODE_LOGS":"C:\\Users\\662176\\AppData\\Roaming\\Code\\logs\\20180128T135030"},"isInitialStartup":true,"workspace":{"id":"7891b2680ddd3bffe72b51dcf8621597","configPath":"C:\\Users\\662176\\Documents\\_Projects\\Welcome\\Welcome.code-workspace"},"filesToOpen":[],"filesToCreate":[],"filesToDiff":[],"nodeCachedDataDir":"C:\\Users\\662176\\AppData\\Roaming\\Code\\CachedData\\490ef761b76b3f3b3832eff7a588aac891e5fe80","backupPath":"C:\\Users\\662176\\AppData\\Roaming\\Code\\Backups\\7891b2680ddd3bffe72b51dcf8621597","zoomLevel":-1,"baseTheme":"vs-dark","backgroundColor":"#1e1e1e","perfEntries":["mark","main:started",1517118629546,0,"mark","main:appReady",1517118629680,0,"mark","main:loadWindow",1517118630508,0],"perfStartTime":1517118629546,"perfAppReady":1517118629680,"perfWindowLoadTime":1517118630508}
[2018-01-28 13:50:40.900] [renderer1] [trace] CommandService#executeCommand workbench.action.terminal.toggleTerminal
[2018-01-28 13:50:44.077] [renderer1] [trace] CommandService#executeCommand setContext
[2018-01-28 13:50:51.276] [renderer1] [trace] CommandService#executeCommand workbench.view.extensions
[2018-01-28 13:51:09.454] [renderer1] [trace] CommandService#executeCommand workbench.action.showCommands
[2018-01-28 13:51:12.878] [renderer1] [trace] CommandService#executeCommand workbench.action.showLogs
[2018-01-28 13:51:40.897] [renderer1] [trace] CommandService#executeCommand workbench.view.extensions
[2018-01-28 13:51:42.608] [renderer1] [trace] CommandService#executeCommand workbench.action.showCommands
[2018-01-28 13:51:43.793] [renderer1] [trace] CommandService#executeCommand workbench.action.showLogs
[2018-01-28 13:54:44.405] [renderer1] [trace] CommandService#executeCommand editor.action.clipboardCopyAction
[2018-01-28 13:54:46.321] [renderer1] [trace] CommandService#executeCommand workbench.action.quickOpen`

and main.log:
[2018-01-28 13:50:30.330] [main] [debug] Starting VS Code
[2018-01-28 13:50:30.330] [main] [debug] from: c:\Program Files (x86)\Microsoft VS Code\resources\app
[2018-01-28 13:50:30.333] [main] [debug] args: {"_":[],"help":false,"h":false,"version":false,"v":false,"wait":false,"w":false,"diff":false,"d":false,"add":false,"a":false,"goto":false,"g":false,"new-window":false,"n":false,"unity-launch":false,"reuse-window":false,"r":false,"open-url":false,"performance":false,"p":false,"prof-startup":false,"verbose":false,"logExtensionHostCommunication":false,"disable-extensions":false,"disableExtensions":false,"list-extensions":false,"show-versions":false,"nolazy":false,"skip-getting-started":false,"sticky-quickopen":false,"disable-telemetry":false,"disable-updates":false,"disable-crash-reporter":false,"skip-add-to-recently-opened":false,"status":false,"s":false,"log":"trace"}
[2018-01-28 13:50:30.335] [main] [trace] Resolving machine identifier...
[2018-01-28 13:50:30.335] [main] [trace] Resolved machine identifier: 53c2b3a538c901147f1482cc99a16610cbd2fc336ac728c6a7aa5ab4e0e5826f
[2018-01-28 13:50:35.434] [main] [trace] IPC#vscode-workbenchLoaded
