### ISSUE TITLE
no results since upgrade

### ISSUE THREAD

**Issue by m3l7** [Microsoft/vscode-tslint#201] opened 2017-05-08 13:24 UTC
since some times (I think after upgrading vscode, but I'm not sure), tslint extension stopped working, giving no results (tslint from command line or from a build task is working).

OS: arch linux
vscode: 1.14.1
tslint: 5.2.0 -- tried with 3.15.1 too (installed locally)
typescript: 2.3.2 (installed locally)

I'm testing with this file:

    import * as _ from "lodash"

which is missing the semicolon.

I tried many different tslint.json, still no results. Here is the debug output:

        [Trace - 2:58:40 PM] Sending request 'initialize - (0)'.
        Params: {
            "processId": 4275,
            "rootPath": "/mnt/dati/Filippo/Sorgenti/techmass-backend",
            "rootUri": "file:///mnt/dati/Filippo/Sorgenti/techmass-backend",
            "capabilities": {
                "workspace": {
                    "applyEdit": true,
                    "workspaceEdit": {
                        "documentChanges": true
                    },
                    "didChangeConfiguration": {
                        "dynamicRegistration": false
                    },
                    "didChangeWatchedFiles": {
                        "dynamicRegistration": false
                    },
                    "symbol": {
                        "dynamicRegistration": true
                    },
                    "executeCommand": {
                        "dynamicRegistration": true
                    }
                },
                "textDocument": {
                    "synchronization": {
                        "dynamicRegistration": true,
                        "willSave": true,
                        "willSaveWaitUntil": true,
                        "didSave": true
                    },
                    "completion": {
                        "dynamicRegistration": true,
                        "completionItem": {
                            "snippetSupport": true
                        }
                    },
                    "hover": {
                        "dynamicRegistration": true
                    },
                    "signatureHelp": {
                        "dynamicRegistration": true
                    },
                    "references": {
                        "dynamicRegistration": true
                    },
                    "documentHighlight": {
                        "dynamicRegistration": true
                    },
                    "documentSymbol": {
                        "dynamicRegistration": true
                    },
                    "formatting": {
                        "dynamicRegistration": true
                    },
                    "rangeFormatting": {
                        "dynamicRegistration": true
                    },
                    "onTypeFormatting": {
                        "dynamicRegistration": true
                    },
                    "definition": {
                        "dynamicRegistration": true
                    },
                    "codeAction": {
                        "dynamicRegistration": true
                    },
                    "codeLens": {
                        "dynamicRegistration": true
                    },
                    "documentLink": {
                        "dynamicRegistration": true
                    },
                    "rename": {
                        "dynamicRegistration": true
                    }
                }
            },
            "initializationOptions": {
                "nodePath": ""
            },
            "trace": "verbose"
        }

        [Trace - 2:58:41 PM] 'npm config get prefix' value is: /usr
        [Trace - 2:58:41 PM] NODE_PATH value is: /usr/lib/node_modules
        [Trace - 2:58:41 PM] Module tslint got resolved to /mnt/dati/Filippo/Sorgenti/techmass-backend/node_modules/tslint/lib/tslint.js
        [Trace - 2:58:41 PM] Received response 'initialize - (0)' in 1187ms.
        Result: {
            "capabilities": {
                "textDocumentSync": 1,
                "codeActionProvider": true
            }
        }

        [Info  - 2:58:41 PM] Linter is running.
        [Trace - 2:58:41 PM] Sending notification 'initialized'.
        Params: {}

        [Trace - 2:58:41 PM] Sending notification '$/setTraceNotification'.
        Params: {
            "value": "verbose"
        }

        [Trace - 2:58:41 PM] Sending notification 'workspace/didChangeConfiguration'.
        Params: {
            "settings": {
                "tslint": {
                    "alwaysShowRuleFailuresAsWarnings": false,
                    "autoFixOnSave": false,
                    "configFile": "",
                    "enable": true,
                    "exclude": "",
                    "ignoreDefinitionFiles": true,
                    "jsEnable": false,
                    "nodePath": "",
                    "rulesDirectory": "",
                    "run": "onType",
                    "trace": {
                        "server": "verbose"
                    },
                    "validateWithDefaultConfig": false
                }
            }
        }

        [Trace - 2:58:41 PM] Sending notification 'textDocument/didOpen'.
        Params: {
            "textDocument": {
                "uri": "file:///mnt/dati/Filippo/Sorgenti/techmass-backend/src/test.ts",
                "languageId": "javascript",
                "version": 1,
                "text": "import * as _ from \"lodash\"\n"
            }
        }

        [Trace - 2:58:41 PM] Sending request 'textDocument/codeAction - (1)'.
        Params: {
            "textDocument": {
                "uri": "file:///mnt/dati/Filippo/Sorgenti/techmass-backend/src/test.ts"
            },
            "range": {
                "start": {
                    "line": 0,
                    "character": 0
                },
                "end": {
                    "line": 0,
                    "character": 6
                }
            },
            "context": {
                "diagnostics": []
            }
        }

        [Trace - 2:58:41 PM] Received response 'textDocument/codeAction - (1)' in 2ms.
        Result: []

        [Trace - 2:58:42 PM] Received notification 'textDocument/publishDiagnostics'.
        Params: {
            "uri": "file:///mnt/dati/Filippo/Sorgenti/techmass-backend/src/test.ts",
            "diagnostics": []
        }

my current tslint.json:

        {
            "rules": {
                "class-name": true,
                "comment-format": [
                    true,
                    "check-space"
                ],
                "indent": [
                    true,
                    "spaces"
                ],
                "no-unused-variable": true,
                "no-duplicate-variable": true,
                "no-eval": true,
                "no-internal-module": true,
                "no-trailing-whitespace": true,
                "no-unsafe-finally": true,
                "no-var-keyword": true,
                "one-line": [
                    true,
                    "check-open-brace",
                    "check-whitespace"
                ],
                "quotemark": [
                    true,
                    "double"
                ],
                "semicolon": [
                    true,
                    "always"
                ],
                "triple-equals": [
                    true,
                    "allow-null-check"
                ],
                "typedef-whitespace": [
                    true,
                    {
                        "call-signature": "nospace",
                        "index-signature": "nospace",
                        "parameter": "nospace",
                        "property-declaration": "nospace",
                        "variable-declaration": "nospace"
                    }
                ],
                "variable-name": [
                    true,
                    "ban-keywords"
                ],
                "whitespace": [
                    true,
                    "check-branch",
                    "check-decl",
                    "check-operator",
                    "check-separator",
                    "check-type"
                ]
            }
        }

**Comment by kevinbeal** [comment] 2017-05-11 21:20
Same thing happened to me.

I uninstalled and tried to re-install, but now clicking the "install" button in the extensions sidebar just quickly gets disabled, flashes the text "installing" before going back to its previous "install"/not disabled state a quarter second later.

It's as if it's trying to install, but gets blocked somewhere and gives up.

No error messages.

**Comment by egamma** [comment] 2017-05-12 07:54
@kevinbeal your issue looks like this one https://github.com/Microsoft/vscode/issues/26448. Can you confirm that this is the same issue and the problem goes away when following these steps.

**Comment by egamma** [comment] 2017-05-12 08:10
@m3l7 I cannot reproduce pls see below, do you do anything differently. I'm using tslint 5.2, TS 2.3.2. I'm currently running on Windows.

Interestingly the trace show that tslint is runnig, but it doesn't report diagnostics.

![image](https://cloud.githubusercontent.com/assets/172399/25989042/dd68703e-36fa-11e7-9737-cd56fe31c767.png)

**Comment by kevinbeal** [comment] 2017-05-12 15:33
@egamma That worked for me. Thank you so much for the help! :D 💯

**Comment by egamma** [comment] 2017-05-12 15:57
@kevinbeal goodness - closing.

**Closed by egamma** 2017-05-12 15:57 UTC
