### ISSUE TITLE
Auto fixer for ordered-imports does not work with multiline named imports

### ISSUE THREAD

**Issue by adidahiya** [Microsoft/vscode-tslint#164] opened 2017-02-08 12:38 UTC
__vscode-tslint v0.8.1__

autofixer for this works (just needs to re-order lines):

```ts
import { autorun, computed } from "mobx";
import { isEmpty, isEqual } from "lodash";
```

but this doesn't work (needs to re-order statements and add a trailing semicolon):

```ts
import { autorun, computed } from "mobx";
import {
  isEmpty,
  isEqual
} from "lodash";
```

**Comment by egamma** [comment] 2017-02-21 08:07
This is a known limitation. The issue is that in the bottom scenario the autofixes overlap. The vscode-autofixing is currently single pass only and therefore doesn't support overlapping fixes.

I'll mention this in the README and change the title.

**Comment by egamma** [comment] 2017-05-11 15:16
Adressed with https://github.com/Microsoft/vscode-tslint/commit/043604aac0f1783ff164871f3f64d052e4c67d69. Autofix now work in the case of overlaps, but it will only fix the non-overlapping changes in a pass. The user has to trigger another save (which is no possible) to trigger the next round of changes.  This is good enough and I have currently no plans to make auto fix multi-pass automatically, so I'm closing this issue.

The fix will be in the next update.

**Closed** 2017-05-11 15:21 UTC
Labels: bug, enhancement

**Comment by adidahiya** [comment] 2017-05-11 18:06
thanks @egamma!

**Comment by TimBeyer** [comment] 2017-11-03 10:28
@egamma is there a technical limitation to not have multi-pass fixes or is it something that could be implemented with a reasonable amount of effort?

**Comment by egamma** [comment] 2017-11-03 11:26
@TimBeyer needs more investigation, since the autofix code is using the blocking `TextDocumentWillSaveEvent.waitUntil()`.
