### ISSUE TITLE
Error in Dev Console "Activating extension `eg2.tslint` failed"

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode-tslint#258] opened 2017-09-14 12:43 UTC
This error is showing up in the dev console of the latest vs-code insiders.
tslint@5.5.0 is installed locally to the project.

This is causing the tslint extension not to function at all.

```
Activating extension `eg2.tslint` failed: Cannot find module 'vscode-languageclient'.
extensionHost.ts:389 [Extension Host] Here is the error stack:  Error: Cannot find module 'vscode-languageclient'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.G.o._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:411709)
	at Module.require (module.js:498:17)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\John Tsombakos\.vscode-insiders\extensions\eg2.tslint-1.0.5\out\extension.js:14:33)
	at Object.<anonymous> (C:\Users\John Tsombakos\.vscode-insiders\extensions\eg2.tslint-1.0.5\out\extension.js:316:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
```

**Comment by egamma** [comment] 2017-09-14 14:48
@jtsom I've verifed that the module vscode-language-client is bundled with the extension. Can you uninstall and install the extension again and see whether the problem persists.

**Comment by egamma** [comment] 2017-09-20 07:40
Closing, cannot reproduce without additional information.

**Closed by egamma** 2017-09-20 07:40 UTC
