### ISSUE TITLE
No way to enable type checking required for some rules

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/vscode-tslint#161] opened 2017-02-02 11:27 UTC
Some TSLint rules require type checking to be enabled but I can find no way to do so. If these rules are enabled but type checking is not abled then TSLint throws, which breaks everything. See https://github.com/palantir/tslint/issues/2169

#With the TSLint CLI ```--type-check``` does the job but the [npm docs for TSLint](https://www.npmjs.com/package/tslint#type-checking) indicate that it's more complex with the Library.

**Comment by egamma** [comment] 2017-02-02 14:13
This is a duplicate of #70.

**Closed by egamma** 2017-02-02 14:13 UTC
