### ISSUE TITLE
vscode-tslint: Lint is not defined

### ISSUE THREAD

**Issue by tylerhjones** [Microsoft/vscode-tslint#15] opened 2015-12-09 22:47 UTC
![screen shot 2015-12-09 at 3 44 44 pm](https://cloud.githubusercontent.com/assets/2709425/11701286/e3b1b378-9e8b-11e5-8026-fd87d2487d42.png)

Installed tslint version is at 3.1.1 
VS Code version is at  0.10.3

I recieve the above message after installing the tslint package via the VS code pkg installer.

**Comment by tylerhjones** [comment] 2015-12-09 22:53
Typescript compiler on 1.7.3

**Comment by egamma** [comment] 2015-12-10 10:18
Hmm, cannot reproduce this error.

Can you share your tslint.json? Do you have custom rules installed? Can you reproduce this in a `hello world` example, e.g., a single folder with a
greeter.ts
``` typescript
class Greeter {
    constructor(public greeting: string) { }
    greet() {
        return "<h1>" + this.greeting + "</h1>";
    }
};
var greeter = new Greeter( 'Hello, world!');
document.body.innerHTML = greeter.greet();
```
and a tslint.json
``` json
{
    "rules": {
        "quotemark": [true, "double"]
    }
}
```

**Comment by egamma** [comment] 2016-01-12 07:41
Closing cannot reproduce, pls reopen with steps.

**Closed by egamma** 2016-01-12 07:41 UTC
Labels: bug

**Comment by egamma** [comment] 2016-01-13 16:00
@tylerhjones I could reproduce this when using the rules from https://github.com/Microsoft/tslint-microsoft-contrib, which only support tslint 2.x. Could this have been the reason in your setup as well?
