### ISSUE TITLE
Extension won't install

### ISSUE THREAD

**Issue by azarzag** [Microsoft/vscode-tslint#210] opened 2017-05-17 15:49 UTC
Hi there,

The extension was installed and working as of a few days ago. However, yesterday I noticed that it somehow got uninstalled, and I am not able to install it again.

I'm running...

- macOS 10.12.4
- VSCode 1.12.2
- tsc 2.3.2
- tslint 5.2.0
- node 7.10

Thanks!

**Comment by egamma** [comment] 2017-05-18 07:58
Duplicate of https://github.com/Microsoft/vscode/issues/26615 pls see https://github.com/Microsoft/vscode/issues/26459 for a work around.

**Closed by egamma** 2017-05-18 07:58 UTC
Labels: duplicate

**Comment by azarzag** [comment] 2017-05-18 12:15
Thanks! Deleting the extension folder in `~/.vscode/extensions` solved my issue as well.
