### ISSUE TITLE
Cannot read property '1' of undefined' (version 0.11.0)

### ISSUE THREAD

**Issue by m-ghaoui** [Microsoft/vscode-tslint#186] opened 2017-04-03 08:04 UTC
After upgrading TSLint to version 0.11.0, a validator crashes:

```
[Info  - 09:55:58] vscode-tslint: 'Cannot read property '1' of undefined' while validating: c:\inetpub\wwwroot\serviceportal-asp-net-mvc\angular2-bootstrap\src\app\call-back-notes\call-back-note\call-back-note.component.ts stacktrace: TypeError: Cannot read property '1' of undefined
```

I deleted all my node modules (including the global ones) and reinstalled everything. 

I am using the global typescript:

```
"typescript.tsdk": "C:/Users/m.ghaoui/AppData/Roaming/npm/node_modules/typescript/lib",
```

The previous version is working fine. Did something change in tsconfig which renders a setting obsolete?

**Comment by m-ghaoui** [comment] 2017-04-03 08:06
Changed the title of this issue.

**Comment by egamma** [comment] 2017-04-03 08:47
Which version of tslint are you using, since you re-installed I suspect you are getting tslint 5, which was released last week. There are some breaking API changes for rules and not all rules have been updated yet. Can you try to install the tslint 4.5.1 (`npm install tslint@4.5.1`) and see whether the problem still exists.

**Comment by m-ghaoui** [comment] 2017-04-03 09:30
Yes, that works. Thanks for the quick response!

**Comment by egamma** [comment] 2017-04-03 12:10
Thinking about there can be two causes of the failure
- vscode-tslint has an issue with tslint 5.0
- a rule you are using doesn't work with the tslint 5.0 API

From the partial stack trace above it is not clear what the root cause is. To narrow this down, can in you install tslint 5.0 and repro your error again. Then open the development tools (`Help>Toggle Developers`), the full stacktrace should then show up in the Console log.

**Comment by egamma** [comment] 2017-04-12 13:49
closing - assuming this was caused by a rule that has not been converted to tslint 5.0

**Closed by egamma** 2017-04-12 13:49 UTC

**Comment by marius-oprea** [comment] 2017-04-13 02:59
I use tslint npm package v5.1.0 with vscode-tslint v0.12.0 and I still get 'Cannot read property '1' of undefined' error:
`vscode-tslint: 'Cannot read property '1' of undefined' while validating: c:\Work\test5\src\main.ts stacktrace: TypeError: Cannot read property '1' of undefined
    at Rule.SelectorRule [as constructor] (c:\Work\test5\node_modules\codelyzer\selectorNameBase.js:16:25)`

I use the default tslint.json file generated by @angular/cli v1.0.0 and codelyzer v2.1.1

Are you saying it's tslint.json config file fault ?

**Comment by Folkman** [comment] 2017-04-13 20:13
This is the stack trace I have for the same error if maybe it sheds more light on the issue:

```
[Info  - 4:07:17 PM] vscode-tslint: 'Cannot read property '1' of undefined' while validating: /Users/lfolkman/Code/carob2/src/app/settings/permissions/permissions.component.ts stacktrace: TypeError: Cannot read property '1' of undefined
    at Rule.SelectorRule [as constructor] (/Users/lfolkman/Code/carob2/node_modules/codelyzer/selectorNameBase.js:16:25)
    at new Rule (/Users/lfolkman/Code/carob2/node_modules/codelyzer/directiveSelectorRule.js:12:28)
    at Object.loadRules (/Users/lfolkman/Code/carob2/node_modules/tslint/lib/ruleLoader.js:47:32)
    at Linter.getEnabledRules (/Users/lfolkman/Code/carob2/node_modules/tslint/lib/linter.js:199:44)
    at Linter.lint (/Users/lfolkman/Code/carob2/node_modules/tslint/lib/linter.js:76:33)
    at doValidate (/Users/lfolkman/.vscode/extensions/eg2.tslint-0.12.0/server/server.js:376:20)
    at validateTextDocument (/Users/lfolkman/.vscode/extensions/eg2.tslint-0.12.0/server/server.js:292:27)
    at Delayer.d.trigger [as task] (/Users/lfolkman/.vscode/extensions/eg2.tslint-0.12.0/server/server.js:469:9)
    at completionPromise.Promise.then (/Users/lfolkman/.vscode/extensions/eg2.tslint-0.12.0/server/delayer.js:19:35)
```

**Comment by egamma** [comment] 2017-04-14 06:06
@Folkman the exception happens in a codelyzer rule. I suspect you are using tslint version 5. This version of tslint broke some of the rules API and codelyzer hasn't updated yet or you need to get a newer version of codelyzer that supports tslint 5. Installing tslint 4.5 works around this problem.

**Comment by kernwig** [comment] 2017-04-14 20:16
Codelyzer bug: https://github.com/mgechev/codelyzer/issues/277

**Comment by egamma** [comment] 2017-04-16 16:47
@kernwig thanks!
