### ISSUE TITLE
tslint.exclude configuration glob is ignored

### ISSUE THREAD

**Issue by lostfictions** [Microsoft/vscode-tslint#215] opened 2017-06-04 00:23 UTC
I'm using a `tslint.exclude` value of `**/node_modules/**`, but when I go-to-definition for a type that lives in TypeScript's `lib.d.ts`, tslint will still lint the file (and pop up dozens of errors, as in the screenshot below:)

![vsc](https://cloud.githubusercontent.com/assets/567041/26757891/24e575f0-489a-11e7-936c-0a04ca0b8530.png)

Not sure if this is relevant, but I'm using `nvm` and my global Node install folder is resolved via a symlink -- but I'm not sure why this would matter, since `node_modules` is still in the resolved path regardless.

**Comment by egamma** [comment] 2017-06-28 20:15
@lostfictions what version of tslint are you using?

I cannot reproduce this with tslint version 5.4.3 in my setup (not using nvm). There the lib.d.ts file isn't linted. 

I can only reproduce the errors when I rename lib.d.ts to lib.ts. 

I've also verified that the glob pattern `**/node_modules/**` works.

**Comment by wedelgaard** [comment] 2017-06-29 07:45
Having somewhat the same issue. I tried to ignore my "dist" folder by adding this to my .vscode/settings.json file

```
  "tslint.exclude": [
    "**/dist/**",
    "**/node_modules/**"
  ]
```
But tslint keeps complaing in the vs-code terminal problems pane.
<img width="1156" alt="screen shot 2017-06-29 at 09 44 31" src="https://user-images.githubusercontent.com/3899287/27676787-994c27a8-5caf-11e7-955e-2b5e79590dc5.png">

**Comment by egamma** [comment] 2017-06-29 08:58
@wedelgaard I've tried to reproduce it in your setup, but I'm not successful. Please see the recording below. What is different in your setup? Are you also using nvm?

![exclude](https://user-images.githubusercontent.com/172399/27679690-b7951ba2-5cb9-11e7-963b-1b9d16188058.gif)

**Comment by lostfictions** [comment] 2017-06-29 17:47
@egamma sorry, i don't have time to further try to isolate this issue -- tslint has actually stopped working for me entirely in VS Code, complaining that it has failed to load even in projects where both typescript and tslint are installed locally _and_ globally and where tslint can be invoked on the command line (via both the global install and the executable in `node_modules/.bin`) without problems. i've wiped `node_modules` and done a full npm install, double-checked that there's no peer dependency mismatch, and double-checked any possible user and workspace settings in Code that could be interfering -- no dice.

i've simply moved on to [typescript-eslint-parser](https://github.com/eslint/typescript-eslint-parser/), which is more robust, faster, and seems better-tested in almost every respect.

**Comment by egamma** [comment] 2017-06-30 10:26
@lostfictions thanks for your support up to now.

**Comment by egamma** [comment] 2017-09-23 09:39
Closing as a duplicate of #262

**Closed by egamma** 2017-09-23 09:39 UTC
