### ISSUE TITLE
TSLint `--project` option

### ISSUE THREAD

**Issue by arboleya** [Microsoft/vscode-tslint#358] opened 2018-06-20 14:18 UTC
How do I specify the TSLint `--project` flag?
https://palantir.github.io/tslint/usage/cli/#cli-usage

Without it, some problems are not reported, even outside vscode.

But using the flag, everything behaves appropriately (outside vscode).

Thanks

**Comment by egamma** [comment] 2018-06-20 14:21
Closing as a duplicate of https://github.com/Microsoft/vscode-tslint/issues/333. 

Please see the discussion here https://github.com/Microsoft/vscode-tslint/issues/70#issuecomment-298177554.

**Closed by egamma** 2018-06-20 14:21 UTC
Labels: duplicate
