### ISSUE TITLE
TSLint is no longer working in VSCode

### ISSUE THREAD

**Issue by mdenson-dayspring** [Microsoft/vscode-tslint#181] opened 2017-03-29 17:26 UTC
It was working for about 20 days and then stopped so sad. Something must be wonky in my configuration but I am unable to figure it out.

**Versions**

Windows 10
VSCode 1.10.2
vscode-tslint 0.9.0
typescript 2.2.2 (installed with npm i -g)
tslint 4.5.1 (installed locally with yarn)

Any help would be appreciated.

Best,
Matthew

===========================================
[Trace - 10:21:51 AM] Sending request 'initialize - (0)'.
Params: {
    "processId": 6048,
    "rootPath": "c:\\clients\\tros\\portals\\angular",
    "rootUri": "file:///c%3A/clients/tros/portals/angular",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true
            },
            "didChangeConfiguration": {
                "dynamicRegistration": false
            },
            "didChangeWatchedFiles": {
                "dynamicRegistration": false
            },
            "symbol": {
                "dynamicRegistration": true
            },
            "executeCommand": {
                "dynamicRegistration": true
            }
        },
        "textDocument": {
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "completionItem": {
                    "snippetSupport": true
                }
            },
            "hover": {
                "dynamicRegistration": true
            },
            "signatureHelp": {
                "dynamicRegistration": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "definition": {
                "dynamicRegistration": true
            },
            "codeAction": {
                "dynamicRegistration": true
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "documentLink": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true
            }
        }
    },
    "initializationOptions": {
        "nodePath": ""
    },
    "trace": "verbose"
}

[Trace - 10:21:52 AM] 'npm config get prefix' value is: C:\Users\mdenson\AppData\Roaming\npm
[Trace - 10:21:52 AM] NODE_PATH value is: C:\Users\mdenson\AppData\Roaming\npm\node_modules
[Trace - 10:21:53 AM] Module tslint got resolved to c:\clients\tros\portals\angular\node_modules\tslint\lib\index.js
[Trace - 10:21:53 AM] Received response 'initialize - (0)' in 2357ms. Request failed: Failed to load tslint library. Please install tslint in your workspace
folder using 'npm install tslint' or 'npm install -g tslint' and then press Retry. (99).
Error data: {
    "retry": true
}

[Info  - 10:21:53 AM] Failed to load the TSLint library.
To use TSLint in this workspace please install tslint using 'npm install tslint' or globally using 'npm install -g tslint'.
You need to reopen the workspace after installing tslint.
[Trace - 10:21:53 AM] Sending request 'shutdown - (1)'.
[Trace - 10:21:53 AM] Received response 'shutdown - (1)' in 1ms.
No result returned.

[Trace - 10:21:53 AM] Sending notification 'exit'.
No parameters provided.

**Comment by egamma** [comment] 2017-03-30 08:29
>typescript 2.2.2 (installed with npm i -g)
>tslint 4.5.1 (installed locally with yarn)

Mixing a global and local install can be the source of problem, can you try whether installing both modules globally or locally fixes the problem. 

You use yarn to install tslint locally,  there is an issue when using yarn globally that is discussed here Microsoft/vscode-eslint#187 that could also be related.

**Comment by evanw** [comment] 2017-04-15 00:32
I just hit this problem too. I got similar output after adding `"tslint.trace.server": "verbose"`.

The problem for us was that we have a local install of `tslint-react` which requires a local install of `tslint`. I know this because I got this stack trace in the VSCode console:

```
Error: Cannot find module 'tslint'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/evan/<evans-project-name>/node_modules/tslint-react/rules/jsxAlignmentRule.js:23:12)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

This dependency is listed in `node_modules/tslint-react/package.json` under `devDependencies` but for whatever reason wasn't actually installed in the local `node_modules` directory. Maybe npm doesn't install `devDependencies` for dependencies? Anyway, I ran `npm install tslint` locally (and `npm install typescript` for the missing peer dependency) and everything started working in VSCode.

Maybe the problem is that `tslint-react` has a bug and `tslint` needs to be a regular dependency instead? Or maybe the problem is that my version of npm (4.2.0) isn't supported? Or maybe even that the `vscode-tslint` extension doesn't set up some path information correctly somehow? It would be nice to know what the underlying bug is so we can actually fix it instead of having it crash and then working around it.

**Comment by gforceg** [comment] 2017-04-17 17:57
I'm have issues with VS Code TSLint and C# for VS Code all the time. Some days it just works. Other days it just doesn't.

I'm often prompted by VS Code to choose between Typescript in my workspace or 'VSCode's version' of typescript... they are both the same version. I wish it would stop popping up these pointless prompts.

This so confusing. I just want it to work.

I'm spending more time trying to figure out why the linters only work when they feel like it than I am working on my projects.

.... frustrated!!!!!

**Comment by egamma** [comment] 2017-05-07 15:35
@evanw I'm trying to reproduce this, but I'm not successful. Is your setup available on github?

> Maybe the problem is that tslint-react has a bug and tslint needs to be a regular dependency instead? 

since tslint-react is a plugin for tslint that provides rules for tslint, having a regular dependency on tslint in a rules plugin would mean you duplicate the tslint install. This is a peer dependency that could be made explicit as in codelyzer

https://github.com/mgechev/codelyzer/blob/master/package.json#L69

**Comment by egamma** [comment] 2017-05-12 13:52
@mdenson-dayspring 

Since you mention yarn this looks like a duplicate of #178 and I'm closing this issue for now.

**Closed by egamma** 2017-05-12 13:52 UTC
