### ISSUE TITLE
vscode-tslint: Cannot read tslint configuration

### ISSUE THREAD

**Issue by wonbyte** [Microsoft/vscode-tslint#124] opened 2016-11-19 21:54 UTC
I am getting the following in vscode; 

vscode-tslint: Cannot read tslint configuration - 'linter.findConfiguration is not a function'

running:
vscode: Version 1.7.1 (1.7.1)
macOS Sierra 10.12.1
tslint@4.0.0 
TSLint plugin 0.5.40

**Comment by Izzmo** [comment] 2016-11-19 23:11
I can reproduce this as well.

**Comment by zachrip** [comment] 2016-11-20 01:52
+1

**Comment by Izzmo** [comment] 2016-11-20 03:00
@wonbyte @zachrip you need to go back down to v3.x. The plugins for vscode, gulp, and grunt, have not been updated to work with v4.x yet.

**Comment by YuichiNukiyama** [comment] 2016-11-20 04:00
Maybe, this [PR](https://github.com/palantir/tslint/pull/1720) is the cause.

**Comment by aleksey-pastuhov** [comment] 2016-11-20 10:22
+1

**Comment by egamma** [comment] 2016-11-20 20:05
Closing as a duplicate of #123.

@YuichiNukiyama the analysis is correct the tslint API has changed in tslint 4.0 and the vscode-tslint extension needs to be adapted.

**Closed by egamma** 2016-11-20 20:05 UTC

**Comment by egamma** [comment] 2016-11-20 20:52
@Izzmo I've created a PR https://github.com/Microsoft/vscode-tslint/pull/125
