### ISSUE TITLE
Problems tab showing inconsistent number of rules, empty rules and rules that has been already resolved.

### ISSUE THREAD

**Issue by victorasantos10** [Microsoft/vscode-tslint#377] opened 2018-08-14 17:35 UTC
- tslint Version: 5.9.1
- typescript Version: 2.7.2
- VSCode version: 1.26.0-insider

![image](https://user-images.githubusercontent.com/8058097/44107802-e751f744-9fce-11e8-8183-134406f11928.png).

Also, the rules aren't related to the opened file. and when I click any of them, nothing happens

I've tried to restart VSCode several times, and it remains happening.

**Comment by egamma** [comment] 2018-08-15 07:42
@victorasantos10 please provide more information about your project setup. What is your linter setup? Do you use tasks with problem matchers to create warnings? Are you sure your TS version is 2.9 and not 3.0 (3.0 is the default in VS Code insiders).

Is there a way I can reproduce what you are observing.

What is confusing in the screenshot is that errors are prefixed with [ts], which indicates that they are coming from TypeScript and not tslint. However, some error like ´magic´ numbers are not TS errors, so you must have a special linter setup. Also I have never seen empty warnings.

**Comment by n3dst4** [comment] 2018-08-15 12:42
I am having this too. I don't _think_ my setup is particularly unusual. I have `tslint@5.11.0`  and `typescript@2.9.2` installed in the project. Whether I pick VSCode's built-in typescript@3.0.1 or the project one, my "Problems" tab contains weird irrelevant reports that don't correspond to anything **but only if there are any linting errors in any open files**. In other words, if there are no real problems, the Problems tab correctly stays empty. But if there is one real problem, I see a crazy list of off reports, `[ts]` rules "nested" under `[tslint]` rules (???) , and nothing responds to clicks. `vscode-tslint` is `1.0.34` and is the only running extension.

This is brand new install of VSCode 1.26.0 on Windows 10, with brand new user settings (I am literally a brand new user to VSCode :) ). I don't know what "tasks with problem matchers" are so I can't answer that part of your enquiry.

Hope this helps! I can try and create a minimal repro repo if that would help you at all?

**Comment by sandy081** [comment] 2018-08-15 15:53
Related to https://github.com/Microsoft/vscode/issues/56317

**Comment by sandy081** [comment] 2018-08-15 17:56
Duplicate of https://github.com/Microsoft/vscode/issues/56371

**Comment by egamma** [comment] 2018-08-16 07:03
Closing this one in favor of the duplicate in VS Code.

**Closed by egamma** 2018-08-16 07:03 UTC
Labels: needs more info
