### ISSUE TITLE
Failed to load the TSLint library

### ISSUE THREAD

**Issue by ccardin9** [Microsoft/vscode-tslint#229] opened 2017-07-10 21:46 UTC
Howdy,

With tslint extension installed as well as typescript (version 2.4.1 globally, 2.3.4 in vscode editor) and tslint (version 5.5.0), vscode does not show the defined rules in my solution's tslint.json files. 

I get the following message in the output console:
```
Failed to load the TSLint library.
To use TSLint in this workspace please install tslint using 'npm install tslint' or globally using 'npm install -g tslint'.
TSLint has a peer dependency on `typescript`, make sure that `typescript` is installed as well.
You need to reopen the workspace after installing tslint.
```

I also get the following message at the top of the editor window when the file loads:
``Using TypeScript (2.3.4) for editor features. TypeScript (2.4.1) is installed globally on your machine. Inconsistent... ``

I am working on a Mac with Sierra OS (v 10.12.5), VSCode (v 1.13.1), VSCode-tslint extension (v 0.16.0), node (v 8.1.2), and npm (v 5.0.3)

I have tried uninstalling and installing node, the extension, and reloaded VS Code multiple times. I have confirmed tslint and typescript are located in my /usr/local/lib/node_modules directory and that  tslint runs from the command line. With all extensions disabled except for VSCode-tslint, the issue continues to occur.

The console in developer tools in VS Code shows the following error:
```Failed to load tslint library. Please install tslint in your workspace
folder using 'npm install tslint' or 'npm install -g tslint' and then press Retry.: Error: Failed to load tslint library. Please install tslint in your workspace
folder using 'npm install tslint' or 'npm install -g tslint' and then press Retry.
    at new ResponseError (/Users/carloscardin/.vscode/extensions/eg2.tslint-0.16.0/node_modules/vscode-jsonrpc/lib/messages.js:40:28)
    at handleResponse (/Users/carloscardin/.vscode/extensions/eg2.tslint-0.16.0/node_modules/vscode-jsonrpc/lib/main.js:305:48)
    at ChildProcess.callback (/Users/carloscardin/.vscode/extensions/eg2.tslint-0.16.0/node_modules/vscode-jsonrpc/lib/main.js:486:13)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:752:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)```

**Comment by manuelnaturalcycles** [comment] 2017-07-12 09:15
Same problem here. I updated VSC from 1.12 to 1.14 and TSLint stopped working throwing the same error: `Failed to load TSLint library. etc...`

**Comment by awakenedguy** [comment] 2017-07-18 19:18
Same here. VSC 1.14.1 and TSLint 5.5.0, TSLint extension 0.16.0, Windows 10, both TS+TSLint are installed globally with "yarn add global", still the same error on VSC startup:
"Failed to load TSLint library"

**Comment by egamma** [comment] 2017-07-19 08:58
@awakenedguy this looks like a duplicate of #178

**Comment by awakenedguy** [comment] 2017-07-19 11:17
@egamma thanks, indeed, the workaround proposed in #178 (specify tslint.nodePath to global node_modules in VSC user settings), solved it.

**Comment by egamma** [comment] 2017-09-14 14:50
The loading of tslint has changed in the latest version of vscode-tslint. The extension now loads the tslint module that is nearest to the linted file. This should have addressed this issue. Please reopen when you still have this problem.

**Closed by egamma** 2017-09-14 14:50 UTC
