### ISSUE TITLE
TS Lint extension doesn't work with the latest Insiders

### ISSUE THREAD

**Issue by thorn0** [Microsoft/vscode-tslint#323] opened 2018-02-15 14:31 UTC
Even though the extension is enabled. It does absolutely nothing. Doesn't show itself in the status bar, doesn't create its Output panel, doesn't lint the source code. Its commands are present in the Command Palette, but if I click it, I get "Error: command 'tslint.showOutputChannel' not found"

![image](https://user-images.githubusercontent.com/94334/36261486-2e9a8656-126d-11e8-9068-cd580573198b.png)

First, I had the 32 bit version of VS Code, but after uninstalling it and installing x64, I got the same situation. Disabling the other extensions doesn't help either. It works fine in the release (non-Insiders) version of VS Code.

- tslint Version: 5.9.1
- typescript Version: 2.5.3, 2.7.1
- VS Code version: Code - Insiders 1.21.0-insider (70e020b2377f12894ca11254548ce365a0e435f1, 2018-02-15T05:17:01.988Z)
- OS: Windows 7 Professional x64

<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.1
ng-template|Ang|0.1.9
vscode-eslint|dba|1.4.5
EditorConfig|Edi|0.12.0
tslint|eg2|1.0.27
prettier-vscode|esb|1.1.3
debugger-for-chrome|msj|4.1.0
autoimport|ste|1.5.3

</details>

**Comment by egamma** [comment] 2018-02-16 14:31
I haven´t seen other reports like this. When you execute ´Show Running Extensions´ does vscode-tslint show up?

Can you please follow the trouble shooting guide and enable tracing
https://github.com/Microsoft/vscode-tslint/blob/master/tslint/README.md#trouble-shooting

**Comment by thorn0** [comment] 2018-02-16 14:49
> When you execute ´Show Running Extensions´ does vscode-tslint show up?

No.

>Can you please follow the trouble shooting guide

No, TSLint's Output panel isn't there.  `command 'tslint.showOutputChannel' not found`

**Comment by egamma** [comment] 2018-02-16 14:55
This means the extension isn´t activated but the there is a package.json that contributes the commands to the command palette. This could hint at a corrupt installation of the extension. Do you see any output in the developer tools Console: Help>Toggle Developer Tools?

This looks similar to https://github.com/Microsoft/vscode-tslint/issues/324.

Can you zip up HOMDE\.vscode\extensions\eg2.tslint-1.0.27 and attach it to the issue?
Then please the folder and re-install the extension again.

**Comment by thorn0** [comment] 2018-02-16 15:08
Yes, there was a message in the dev tools console: `Activating extension `eg2.tslint` failed: Cannot find module 'C:\Users\thorn\.vscode-insiders\extensions\eg2.tslint-1.0.27\out\extension'`

And this file and the whole `out` folder indeed didn't exist. Re-installing the extension didn't change anything. The `eg2.tslint-1.0.27` remained as it was. So I uninstalled the extension, deleted the folder manually, and installed again. Everything seems to be okay now. Not sure what could've led to that situation.

My original eg2.tslint-1.0.27 folder: [eg2.tslint-1.0.27.zip](https://github.com/Microsoft/vscode-tslint/files/1731741/eg2.tslint-1.0.27.zip)

**Comment by egamma** [comment] 2018-02-16 15:13
Looks like a corrupt install so it is a duplicate of #324, closing and we continue to track the issue in the vsode repo.

**Closed by egamma** 2018-02-16 15:13 UTC

**Comment by egamma** [comment] 2018-02-16 15:17
@thorn0 on more thing ...

One more thing can you please attach the log for the shared process to Microsoft/vscode#43813?

This is how to get at the log 
![image](https://user-images.githubusercontent.com/172399/36314318-b87e0d62-1334-11e8-9b47-b678eaf44e5d.png)
