### ISSUE TITLE
Fixing removes comments (without warning)

### ISSUE THREAD

**Issue by davidzaadstra** [Microsoft/vscode-tslint#299] opened 2017-11-29 10:15 UTC
- tslint Version: 5.8.0
- typescript Version: 2.6.0

Steps to Reproduce:

1. Use the following code:
let x: boolean;
if (x) {
  // do something
}
// I like my comments on a separate line, describing the following block
else {
  // do something else
}

2. Use autofix. 

The "I like my comments on a separate line" comment will be removed without warning. This is a problem because it will not make any test fail, but still kind of "break" the code insofar as valuable information might be lost. Which means that I have to manually review all changes made by the fixer.

It would be ok to simply not autofix the issue in those cases and leave it to the user.

**Comment by egamma** [comment] 2017-11-29 16:51
@davidzaadstra do you use autofix from the command line or from inside VS Code?  What rule violation are you auto fixing in this case? 

In general vscode-tslint provides fixers for a small number of rules, but most of the fixers come from tslint and not vscode-tslint. If the issue reproduces when running tslint from the command line, then it is an issue with the fixer provided by tslint and not by vsocde-tslint.

**Comment by davidzaadstra** [comment] 2017-11-29 17:05
It's the one-line rule (the "else" is the offending line here). 
It happens on the command line, too.

I entered the issue here because I wasn't sure about the implementation, and also I believe it might be a good idea to get some feedback in the VS Code UI.

**Comment by egamma** [comment] 2017-11-29 17:23
When it happens on the command line, then please report the issue against the tslint repository, since it is a tslint fixer that has this behaviour.

Closing this issue as an upstream issue.

**Closed by egamma** 2017-11-29 17:23 UTC
Labels: upstream
