### ISSUE TITLE
How to enable type checking

### ISSUE THREAD

**Issue by pburridge** [Microsoft/vscode-tslint#226] opened 2017-07-04 16:34 UTC
I am getting the following warnings

```
Warning: The 'no-use-before-declare' rule requires type checking
Warning: The 'no-unused-variable' rule requires type checking
```

After investigation these rules require type checking to be enabled in tslint.

Normally I would call tslint with --type-check, how can this be achieved when using vscode-tslint?

Thanks.

**Comment by egamma** [comment] 2017-07-05 08:45
@pburridge this is a duplicate of #70, please see the discussion over there.

**Closed by egamma** 2017-07-05 08:45 UTC
Labels: duplicate
