### ISSUE TITLE
VS Code Settings seems to not match the code

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode-tslint#4] opened 2015-11-19 19:38 UTC
It looks to me that the settings specified in [package.json](https://github.com/Microsoft/vscode-tslint/blob/master/tslint/package.json#L35-L46), especially the `options` property is not picked up by your [code](https://github.com/Microsoft/vscode-tslint/blob/master/tslint-server/src/server.ts#L155-L164).

`package.json` specifies `tslint.enable` and `tslint.options`, but in the code it looks like `options` is not used and it is `rulesDirectory` and `formatterDirectory`.

Maybe I'm wrong, but passing in options does not seem to work for me.

**Comment by egamma** [comment] 2015-11-21 11:12
Duplicate of #6

**Closed by egamma** 2015-11-21 11:12 UTC
