### ISSUE TITLE
Add auto fix option

### ISSUE THREAD

**Issue by erikvullings** [Microsoft/vscode-tslint#12] opened 2015-12-01 22:35 UTC
TSlint generates many warnings for things that would be easy to fix automatically, such as missing whitespace, superfluous whitespace, e.g. at the end of a sentence, double vs single quotes, missing semi colons, missing braces around single line statements, etc. Is there an option to fix these automatically, or could you add such an option?

**Comment by egamma** [comment] 2015-12-02 08:34
I'm not aware of such an option in tslint. JSCS provides such an option (--fix) and the JSCS integration exposes a corresponding action. tslint itself is the right source for a fix option. Once tslint provides such an option then tslint integration will do the same and expose it.

Closing the issue, pls reopen when tslint provides a --fix option.

**Closed by egamma** 2015-12-02 08:34 UTC

**Comment by shrutiaggarwal3012** [comment] 2016-02-23 11:15
so for now tslint errors has to be manually fixed ?

**Comment by egamma** [comment] 2016-02-23 15:52
yes, sorry. The issue is that tslint has the knowledge about the error and can suggest a fix. The vscode-tslint extension that integrates tslint doesn't have this understanding of an error. Therefore, please file a feature request against tslint.

**Comment by JoshuaKGoldberg** [comment] 2016-03-25 23:06
https://github.com/palantir/tslint/issues/561
